# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: db/winter-2018-order.csv

test:
  adapter: postgresql
  database: db/winter-2018-order.csv


production:
  adapter: postgresql
  database: db/winter-2018-order.csv
  host: localhost
